version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    versioning-strategy: increase
    groups:
      dev-tools:
        dependency-type: development
    labels: ["dependencies"]
    commit-message:
      prefix: "chore"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: ["dependencies"]
    commit-message:
      prefix: "chore"
